seed: 42

paths:
  train_csv: datasets/covid19-global-forecasting-week-1/train.csv
  test_csv: datasets/covid19-global-forecasting-week-1/test.csv

features:
  drop: ["Date"]
  numeric: ["Lat", "Long"]
  categorical: ["Province/State", "Country/Region"]

train:
  test_size: 0.2
