seed: 42

# Dataset
paths:
  train_csv: datasets/covid19_global_forecasting_week_1/train.csv
  test_csv: datasets/covid19_global_forecasting_week_1/test.csv
  
# Features (Comment out the feature you don't want to add)
features:
  save_df_dir: datasets/covid19_feature_extraction
  save_filename: sample_features.csv

features_to_apply:
  - TimeDelayFeatures
  - DayFeatures
  - DistanceToOriginFeatures
  - CountryAreaFeatures
  - CountryPopulationFeatures
  - CountrySmokingRateFeatures
  - CountryHospitalBedsFeatures
  - CountryHealthExpenditureFeatures

# Feature Params
feature_params:
  TimeDelayFeatures:
    days_history_size: 30

  DayFeatures:
    thresholds: [1, 10, 100]

  DistanceToOriginFeatures:
    origin_province: Hubei

  CountryAreaFeatures:
    source_url: http://api.worldbank.org/v2/en/indicator/AG.LND.TOTL.K2?downloadformat=csv
    zip_filename: area.zip
    known_filename: API_AG.LND.TOTL.K2_DS2_en_csv_*.csv   # ignore version
    out_dir: datasets/external_data/area
    left_on: Country/Region        
    right_on: Country Name   

  CountryPopulationFeatures:
    source_url: https://github.com/ordinaryevidence/leep-cea/raw/refs/heads/master/WPP2019_PopulationByAgeSex_Medium.zip
    zip_filename: WPP2019_PopulationByAgeSex_Medium.zip
    known_filename: WPP2019_PopulationByAgeSex_Medium*.csv
    out_dir: datasets/external_data/population
    left_on: Country/Region
    right_on: Location
    time_from: 2014-01-01
    time_to: 2019-01-01

  CountrySmokingRateFeatures:
    source_url: http://api.worldbank.org/v2/en/indicator/SH.PRV.SMOK?downloadformat=csv
    zip_filename: smoking.zip
    known_filename: API_SH.PRV.SMOK_DS2_en_csv_*.csv
    out_dir: datasets/external_data/smoking
    left_on: Country/Region          
    right_on: Country Name    

  CountryHospitalBedsFeatures:
    source_url: http://api.worldbank.org/v2/en/indicator/SH.MED.BEDS.ZS?downloadformat=csv
    zip_filename: hospital_beds.zip
    known_filename: API_SH.MED.BEDS.ZS_DS2_en_csv_*.csv
    out_dir: datasets/external_data/hospital_beds
    left_on: Country/Region          
    right_on: Country Name    

  CountryHealthExpenditureFeatures:
    source_url: http://api.worldbank.org/v2/en/indicator/SH.XPD.CHEX.PP.CD?downloadformat=csv
    zip_filename: health_expenditure.zip
    known_filename: API_SH.XPD.CHEX.PP.CD_DS2_en_csv_*.csv
    out_dir: datasets/external_data/health_expenditure
    left_on: Country/Region          
    right_on: Country Name   


# Train
train:
  # eval_size: 0.2  # not necessary
  save_model_dir: models
  save_log_dir: logs
  last_train_date: 2020-03-11
  last_eval_date: 2020-03-24
  cat_features: ["Province/State", "Country/Region"]
  model: CatBoost   # Choose the model type you want to train

# Test 
test:
  last_test_date: 2020-04-23
  cat_features: ["Province/State", "Country/Region"]

# Models
models:
  CatBoost:
    type: CatBoostRegressor
    params:
      iterations: 1000
      has_time: true
      depth: 8
      learning_rate: 0.05

  # LightGBM:
  #   type: LGBMRegressor
  #   params:
  #     n_estimators: 1000
  #     learning_rate: 0.05
  #     max_depth: -1
  #     num_leaves: 31

  # XGBoost:
  #   type: XGBRegressor
  #   params:
  #     n_estimators: 1000
  #     learning_rate: 0.05
  #     max_depth: 6
